### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by heckad**
If `MINGW `not defined then the CMake think that `MINGW` is string. https://cmake.org/pipermail/cmake/2011-October/046939.html

### CODE REVIEW

**Comment by heckad** [comment]
@chronoxor?

**Comment by chronoxor** [comment]
I have no issues with building latest MinGW-64, MSYS2, Cygwin and VS2019 with the current script version. I use cmake 3.18.2 for this.

**Comment by heckad** [comment]
I got 
```
CMake Error at cmake/SetPlatformFeatures.cmake:29 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
```
when I run `C:\Users\Asus\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-0\202.7319.72\bin\cmake\win\bin\cmake.exe -DCMAKE_BUILD_TYPE=Debug --verbose -G "CodeBlocks - NMake Makefiles" C:\Users\Asus\Documents\Projects\cpp\CppTrader`

It's because `if(MINGW OR CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION STREQUAL "")` returned false.

CMake version: 3.17.3

Also in my case, if I add
```
  if(NOT DEFINED MINGW)
    message("not mingw")
  endif()

  if(NOT DEFINED CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION)
    message("not vs")
  endif()
```
I got
```
not mingw
not vs
```
in console.

**Comment by chronoxor** [comment]
Which is your cmake version?

**Comment by chronoxor** [comment]
Can you try this?
```
if(MINGW OR NOT CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION OR CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION STREQUAL "")
```

**Comment by heckad** [comment]
> Which is your CMake version?

3.17.3


> Can you try this?

Yes, it's work.

**Pull request closed without merging**
